version: '3'

networks:
  web:

services:
  app:
    image: node:12.10.0-alpine
    volumes:
      # aplicação
      - ./app:/app
    working_dir: /app
    command: npm start
    networks:
      - web
  
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      # - ./web:/usr/share/nginx/html
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app